# Generated by Django 6.0.2 on 2026-04-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('link', models.CharField(help_text='Ссылка на сайт или ссылка на инстаграм или что то еще', max_length=255, verbose_name='Ссылка на партнера')),
                ('logo', models.ImageField(upload_to='partners/')),
            ],
            options={
                'verbose_name': 'партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
    ]
