# Generated by Django 6.0.2 on 2026-02-22 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='perent',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_availavel',
            new_name='is_available',
        ),
    ]
