# Generated by Django 6.0.2 on 2026-02-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='order',
        ),
        migrations.AddField(
            model_name='partner',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
